In [11]:
import pandas as pd 
import numpy as np

In [12]:
df = pd.read_csv('CarPrice_Assignment.csv')
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

Data cleaning

In [38]:
df['st'].unique()

array([111, 154, 102, 115, 110, 140, 160, 101, 121, 182,  48,  70,  68,
        88, 145,  58,  76,  60,  86, 100,  78,  90, 176, 262, 135,  84,
        64, 120,  72, 123, 155, 184, 175, 116,  69,  55,  97, 152, 200,
        95, 142, 143, 207, 288,  73,  82,  94,  62,  56, 112,  92, 161,
       156,  52,  85, 114, 162, 134, 106])

In [14]:
df.drop('car_ID',inplace=True,axis = 1)

In [15]:
df.drop('CarName',inplace=True,axis = 1)

In [16]:
df.dtypes

symboling             int64
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [17]:
df.drop(columns=['carlength','carwidth','carheight'],inplace= True,axis = 1)

In [18]:
df[['wheelbase','boreratio','stroke','compressionratio','price']] = df[['wheelbase','boreratio','stroke','compressionratio','price']].astype(int)

In [40]:
df['stroke'].unique()

array([2, 3, 4])

In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import  make_column_transformer
from sklearn.model_selection import  train_test_split 
from sklearn.pipeline import  make_pipeline 
from sklearn.preprocessing import  StandardScaler

In [21]:
x = df.drop('price',axis = 1)
y = df['price']

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state = 689)

In [23]:
from sklearn.linear_model import  LinearRegression

In [24]:
lr = LinearRegression()

In [25]:
tr = make_column_transformer(
    (OneHotEncoder(sparse_output= False,handle_unknown= 'ignore'),[1,2,3,4,5,6,9,10,12]),
    (StandardScaler(),[0,7,8,11,13,14,15,16,17,18,19]),
    remainder='passthrough'    
)


In [26]:
pipe = make_pipeline(tr,lr)

In [27]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 2, 3, 4, 5, 6, 9, 10,
                                                   12]),
                                                 ('standardscaler',
                                                  StandardScaler(),
                                                  [0, 7, 8, 11, 13, 14, 15, 16,
                                                   17, 18, 19])])),
                ('linearregression', LinearRegression())])

In [28]:
pipe.fit(x_train,y_train) 

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 2, 3, 4, 5, 6, 9, 10,
                                                   12]),
                                                 ('standardscaler',
                                                  StandardScaler(),
                                                  [0, 7, 8, 11, 13, 14, 15, 16,
                                                   17, 18, 19])])),
                ('linearregression', LinearRegression())])

In [29]:
y_pred = pipe.predict(x_test)

In [30]:
y_pred

array([ 8065.38914034,  7386.6859522 ,  6762.94284018, 11420.14032202,
       11742.61794774, 25615.98518015,  5739.91865304, 14012.0209828 ,
        7992.83545484, 44454.58622013, 10915.35272328, 11010.69062589,
       25115.74568822,  6687.84408222, 12337.88503859,  6849.20865871,
       37015.72677511,  7878.60128575, 18268.02686043,  6811.52713376,
        8329.01651752,  8121.32177237,  8923.18505085, 13043.17702882,
       15103.78701442, 19356.63628382,  5931.44298134,  6936.86114037,
       10921.39476844, 14917.41695367,  9835.95757031, 10932.18904253,
        5904.48491305, 16446.13607182,  6285.97713559, 15826.07474089,
        3682.45662929, 10486.70803341, 31043.44954225,  8606.90452719,
        9282.16703847])

In [31]:
from sklearn.metrics import r2_score 

In [32]:
print(r2_score(y_pred,y_test))

0.9610103259055037


In [33]:
# finding best random state  during creating model

score = []
for i in range(1000):
    X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size= 0.2,random_state= i)
    model = LinearRegression()
    pip = make_pipeline(tr,model)
    pip.fit(X_train,Y_train)
    y_pre = pip.predict(X_test)
    score.append(r2_score(Y_test,y_pre))

In [34]:
np.argmax(score)

np.int64(689)

In [35]:
score[np.argmax(score)]

0.9587965401136583

In [36]:
import pickle

In [37]:
with open('Linear_model.pkl', 'wb') as file:
    pickle.dump(pipe,file)